# Generated by Django 4.2.1 on 2023-05-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_api', models.CharField(max_length=200)),
                ('type_api', models.CharField(default='GET', max_length=200)),
            ],
        ),
    ]
